import localFont from "next/font/local";
import style from "./styles/general.scss"
import Footer from "./components/footer";
import Header from "./components/header";


export const metadata = {
  title: "Anime Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
