import localFont from "next/font/local";
import style from "./styles/general.scss"
import Footer from "./components/footer";
import Header from "./components/header";
import StyleVariables from "./styles/variables.scss"
import { Montserrat} from 'next/font/google'
 import Image from "next/image";
const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: "Anime Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <Header/>
    
      <section className="main-container">
        {children}
        <div className="go-to-top">
          <a href="#header">
          <Image src="/patterns/arrow.png" height={50} width={50}/>
          </a>
          </div>
          </section>
        <Footer/>
      </body>
    </html>
  );
}
